name: Lambda Build
on:
  workflow_call:
  
  push:
    branches:
      - main
      - feature/*
      - debug/*
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Make Package
        run: |
          make init
          make requirements-all
          make test
      
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report/**

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Make Package
        run: |
          make init
          make requirements-all
          make package
      
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda
          path: pkg/deployment-package.zip