name: Lambda deploy
on:
  workflow_dispatch:
    push:
      branches:
        - main
        - feature/*
        - debug/*
      paths:
        - src/**
jobs:
  Build:
    uses: ./.github/workflows/build.yml
    name: Build Artifacts

  Deploy-Source:
    uses: ./.github/workflows/deploy-source.yml
    name: Deploy Source
    needs: Build
    secrets: inherit